[package]
name = "crc-any"
version = "2.1.1"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/crc-any"
homepage = "https://magiclen.org/crc-any"
keywords = ["hash", "crc", "crc16", "crc32", "crc64"]
categories = ["no-std", "algorithms"]
description= "To compute CRC values by providing the length of bits, expression, reflection, an initial value and a final xor value. It has many built-in CRC functions."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/crc-any", branch = "master" }
appveyor = { repository = "magiclen/crc-any", branch = "master", service = "github" }

[dependencies]
debug-helper =  "0.1"

[dev-dependencies]
bencher = "0.1.5"

[features]
development = []

[[bench]]
name = "bench"
harness = false